### PR TITLE
Fixes numpy encoding errors

### PR DESCRIPTION
**Pull request by lukecampbell**
I don't even know where to begin describing this bug.

Here is the outgoing granule before encoding

```
{'domain': (10,), 'data_producer_id': '', 'connection_index': '',
'record_dictionary': {1: array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,
8.,  9.]), 2: None, 3: None, 4: None, 5: None, 6: None, 7: None, 8:
None, 9: None, 10: None, 11: None, 12: None, 13: None, 14: None, 15:
None, 16: None, 17: None, 18: None, 19: None}, 'connection_id': '',
'locator': None, 'type_': 'Granule', 'param_dictionary':
'9a1f8b57e7af41479d42ce0764ad4ec1', 'creation_timestamp':
1365446562.004057, 'provider_metadata_update': {}}
```

Here it is after encoding

```
><> {'domain': [10], 'data_producer_id': '', 'connection_index': '',
>'record_dictionary': {1: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0,
>9.0], 2: None, 3: None, 4: None, 5: None, 6: None, 7: None, 8: None, 9:
>None, 10: None, 11: None, 12: None, 13: None, 14: None, 15: None, 16:
>None, 17: None, 18: None, 19: None}, 'connection_id': '', 'locator':
>None, 'type_': 'Granule', 'param_dictionary':
>'9a1f8b57e7af41479d42ce0764ad4ec1', 'creation_timestamp':
>1365446562.004057, 'provider_metadata_update': {}}
```

The numpy array was converted into a list and it turns out it stemmed
from the IonObject's overloading the setattr which is dynamically
attached at runtime inside registry.py and the walker bypasses walk and
somehow converts the numpy array into a list because numpy has **iter**.

Dave F suggested we use walk here so I implemented it using walk and now
granules flow again without bugs.

### CODE REVIEW

**Comment by lukecampbell** [comment]
This bug is preventing the transport of granules correctly. And it is an extension of this PR:
https://github.com/ooici/pyon/pull/298

**Comment by lukecampbell** [comment]
[This is where the culprit lives](https://github.com/ooici/pyon/blob/master/pyon/core/registry.py#L152)

`numpy` arrays extend `__iter__` and the `recusive_encoding` method converts the array in both the caller and the local object.

Here's an example of what's happening

When the deserializer iterates over the dictionary containing the granule it runs setattr(ion_obj, k,v) on all the field/values for the dictionary against the ion object, which in this case is a Granule.

The setattr is overridden and somehow coerces the numpy array into a list.

Can someone please take a look at the PR and make sure it's correct, I know based on an earlier PR that there was an issue with utf-8 keys and values but I'm out of the loop on the context; all I know is that until it's resolved we can't visualize some data products and I can't test a lot of components.

```
><> from interface.objects import Granule

><> g = Granule()

><> granule = rdt.to_granule()

><> vars(granule)['record_dictionary']
-->
{1: None,
 2: None,
 3: None,
 4: None,
 5: None,
 6: None,
 7: None,
 8: None,
 9: array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]),
 10: None,
 11: None,
 12: None,
 13: None,
 14: None,
 15: None,
 16: None,
 17: None,
 18: None,
 19: None}

><> for k,v in vars(granule).iteritems():
    setattr(g,k,v)
...

><> vars(g)['record_dictionary']
-->
{1: None,
 2: None,
 3: None,
 4: None,
 5: None,
 6: None,
 7: None,
 8: None,
 9: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0],
 10: None,
 11: None,
 12: None,
 13: None,
 14: None,
 15: None,
 16: None,
 17: None,
 18: None,
 19: None}

><> vars(granule)['record_dictionary']
-->
{1: None,
 2: None,
 3: None,
 4: None,
 5: None,
 6: None,
 7: None,
 8: None,
 9: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0],
 10: None,
 11: None,
 12: None,
 13: None,
 14: None,
 15: None,
 16: None,
 17: None,
 18: None,
 19: None}
```

**Comment by pkediyal** [comment]
many issues for unicode to utf-8 here.

(1) a string would become None, because the utf8fix returns that for non-unicode
(2) does not convert dictionary keys to utf8 encoding
(3) bypasses numpy array, am not sure if numpy array's content also need to be utf-8 encoded.

**Comment by lukecampbell** [comment]
if the contents of an array are unicode they MUST be left that way.  The numpy container must be unaltered in any way. No component in the system should be allowed to alter the content of the numpy array container.  I'm fine with doing whatever you guys want to fix this but as it stands right now granules are throwing out numpy arrays which is causing a ton of problems for me.

**Comment by pkediyal** [comment]
Fully understand that Luke, we do need to fix it. The easiest fix is to revert to my solution only that we add an if condition that ignores numpy arrays (like in walk). But then we have a "walk" duplicate. So I am working on an enhanced walk that addresses the requirement from Michael regarding encoding keys in dicts as well (walk leaves dict keys untouched).

**Comment by lukecampbell** [comment]
Potentially resolved by https://github.com/ooici/pyon/pull/319

**Pull request closed without merging**
