### PR TITLE
Adds hash_any to pyon

### PR DESCRIPTION
**Pull request by lukecampbell**

### CODE REVIEW

**Comment by daf** [comment]
Two thoughts:
- since this doesn't depend on pyon, consider putting it in `putil/` which doesn't auto-gevent-monkey-patch
- any way to get the numpy import isolated into a smaller section so this is mostly functional without numpy?

**Comment by daf** [comment]
Also if the Import fails, this method should still exist/return something.

**Comment by blazetopher** [comment]
Dave - how's it looking now?

**Comment by daf** [comment]
:shipit:

**Pull request merged**
