### PR TITLE
Container Exchange API w/ auto EMS usage

### PR DESCRIPTION
**Pull request by daf**
This PR represents a major refactor to support the Container's Exchange Manager class and is wholly contained within pyon.  If EMS (via coi-services) is present in the system, Exchange Manager will interact with it and allow the EMS to do the actual bare-metal work.

This should be mergeable with MINIMAL disruption to anyone - using the container XO is currently a buy-in style - you have to explicitly use it.

Some major pieces touched:
- Beginnings of a Transport layer refactor, which `pyon.net.channel` is built on top of. Abstracts actual bare-metal interactions and allows redirection (for the container's exchange manager to make decisions on).
- `pyon.net.endpoint` improvements:
  - `SendingBaseEndpoint` to mirror listening side - all send-first endpoints based on this
  - `to_name` and `from_name` kwargs where it makes sense
- Full Container Exchange Object testing (UNIT/INT, group='exchange')

Several TODOs remain and will be incorporated as time allows:
- Tests for Transport layer
- Finish porting Transport layer fully (some remaining AMQP interactions in Channel layer)
- AcceptedChannel needs underlying transport/nametrio
- Tests for pubsub via XP (to establish pattern)
- Container ExManager should cache any AMQP interaction for no duplicates
- Switch service clients to use XOs automatically (will be done soon)
- `delete_<x>_by_name` API

### CODE REVIEW

**Comment by daf** [comment]
Wait, may have missed something.

**Comment by daf** [comment]
Testing/fixing coi-services now to coincide.

**Comment by daf** [comment]
Several integration points to work out with in coi-services.  Waiting until tomorrow to fix up.

**Comment by mmeisinger** [comment]
I've had a look through the changes and it all looks sound and good to me. Excellent job. Please merge asap when ready. I'm looking forward to having these abstractions in the code base

**Pull request merged**
