### PR TITLE
implement conversation log

### PR DESCRIPTION
**Pull request by pkediyal**
rebased version

### CODE REVIEW

**Comment by pkediyal** [comment]
the pointer to appropriate ion-def needs to be in place

**Comment by shenrie** [comment]
For an initial implementation, this looks good. How best to merge?

---

Stephen P. Henrie  mailto:shenrie@ucsd.edu
System Architect
Ocean Observatories Initiative Cyberinfrastructure Project: http://ci.oceanobservatories.orghttp://ci.oceanobservatories.org/

**Comment by pkediyal** [comment]
I updated the pointer of the submodule so merge should be automatic, let me know if you have a problem now.

**Comment by shenrie** [comment]
Looks like there is still and issue with this PR and being able to merge it.

---

Stephen P. Henrie  mailto:shenrie@ucsd.edu
System Architect
Ocean Observatories Initiative Cyberinfrastructure Project: http://ci.oceanobservatories.orghttp://ci.oceanobservatories.org/

**Comment by pkediyal** [comment]
what is the problem?

**Comment by shenrie** [comment]
You tell me…it says it can't be merged automatically.

---

Stephen P. Henrie  mailto:shenrie@ucsd.edu
System Architect
Ocean Observatories Initiative Cyberinfrastructure Project: http://ci.oceanobservatories.orghttp://ci.oceanobservatories.org/

**Comment by pkediyal** [comment]
i mean what do you see?

**Comment by pkediyal** [comment]
any message?

**Comment by pkediyal** [comment]
I can only imagine that the earlier commit is causing a problem because it does not have the bumped up ion-def, if you could squash the two commits then it would be good to go. this is why i had said I needed the ion-def pr first but you asked me to push so you can review the code. Anyway, if you can't squash the two commits into one I will retract the pull request squash it and then create another one.

**Pull request merged**
