### PR TITLE
OOIION-1753: Add pending channel numbers to Node for insulation

### PR DESCRIPTION
**Pull request by daf**
When requesting a channel number from Pika, when the correct set of circumstances leads to a channel not being fully allocated, our channel number selector wouldn't know about it but would cause Pika to crash, failing the container.

This adds a layer of insulation to ensure when a channel number is handed out, it won't be handed out again until it completes a round trip from Pika and gets wrapped by our AMQPTransport class.

This is to help solve the AMQCHAN IS NONE THIS SHOULD NEVER HAPPEN issues that occur from spurious greenlet interleaving with pika.

### CODE REVIEW

**Comment by daf** [comment]
@jamie-cyber1 @mmeisinger Please review (vs master)

**Comment by mmeisinger** [comment]
Please rename PR with Jira as prefix

**Comment by mmeisinger** [comment]
:+1: Looks good. Can it be merged?

**Comment by jamie-cyber1** [comment]
We still need to make sure tests don't fail on REL2.0.  If it helps the stability of test running, it should be merged.

**Comment by jamie-cyber1** [comment]
Please document pull requests in jira, Dave.

**Pull request merged**
