### PR TITLE
OOIION-1786: Make message encoding interceptor more efficient

### PR DESCRIPTION
**Pull request by mmeisinger**

### CODE REVIEW

**Comment by mmeisinger** [comment]
@jamie-cyber1 please merge

**Comment by daf** [comment]
Why bother keeping `pyon/core/interceptor/codec.py` around if it's just commented out?

**Comment by jamie-cyber1** [comment]
This can't be merged.

**Comment by mmeisinger** [comment]
PR updated and rebased. tests pass

**Pull request merged**
