### PR TITLE
modify walk to handle dicts and list instead of all __iter__ ables;

### PR DESCRIPTION
**Pull request by pkediyal**
Here is a thing Dave/Luke need to give some input on as well. The current solution is different from Luke's in a subtle way.

Earlier, in recursive_encoding the transformation occurred on the reference to the dict that had been passed in. Now, the transformation is of the dict. This means recursive_encoding changes by value not by reference (one has to pardon loose and ambiguous use of terms here because python passes by value but in case for dict the value is the reference). To unambiguously see what I mean notice the changes in the test_object.py included in the commit.

The solution isn't doing something incorrect, but a change is a change in behavior and in this case it happens due to the way walk behaves.

Our tests in coi-services and pyon and Luke's tests pass though, and I don't expect a problem.

### CODE REVIEW

**Comment by daf** [comment]
:thumbsup: Looks good to me

**Comment by lukecampbell** [comment]
:metal: If the test passes then DM should be fine!

**Comment by shenrie** [comment]
If the tests pass, then I will merge and we will hope for the best and fix if something is broke.

---

Stephen P. Henrie  mailto:shenrie@ucsd.edu
System Architect
Ocean Observatories Initiative Cyberinfrastructure Project: http://ci.oceanobservatories.orghttp://ci.oceanobservatories.org/

**Comment by lukecampbell** [comment]
I appreciate you guys thoroughly testing and verifying this, I know it's a pain but it'll save us a lot of time debugging.

**Pull request merged**
